
-- Exemplo de INNER JOIN juntando duas tabelas em uma através de igualdade de um campo em comum em ambas tabelas
WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT 'TOKIO' AS CITY, 'TOKIO' AS STATE
UNION ALL SELECT 'MUMBAY' AS CITY, 'MAHARASHIRA' AS STATE),
FROM_ITEM_B AS
(SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKIO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A 
INNER JOIN FROM_ITEM_B 
ON FROM_ITEM_A.STATE = FROM_ITEM_B.STATE;

-- Exemplo de INNER JOIN juntando duas tabelas em uma através de diferença de um campo em comum em ambas tabelas
WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT 'TOKIO' AS CITY, 'TOKIO' AS STATE
UNION ALL SELECT 'MUMBAY' AS CITY, 'MAHARASHIRA' AS STATE),
FROM_ITEM_B AS
(SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKIO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A 
INNER JOIN FROM_ITEM_B 
ON FROM_ITEM_A.STATE != FROM_ITEM_B.STATE;

-- Exemplo de CROSS JOIN trazendo todas as combinações possíveis com os itens de duas tabelas, mesmo elas se relacionando ou não
WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT 'TOKIO' AS CITY, 'TOKIO' AS STATE
UNION ALL SELECT 'MUMBAY' AS CITY, 'MAHARASHIRA' AS STATE),
FROM_ITEM_B AS
(SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKIO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A 
CROSS JOIN FROM_ITEM_B;

-- Exemplo replicando o efeito do CROSS JOIN sem chamar a função exbindo apenas os resultados possíveis de ambas as tabelas
WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT 'TOKIO' AS CITY, 'TOKIO' AS STATE
UNION ALL SELECT 'MUMBAY' AS CITY, 'MAHARASHIRA' AS STATE),
FROM_ITEM_B AS
(SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKIO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A, FROM_ITEM_B;

-- Exemplo de OUTER JOIN que traz todos os item de ambas as tabelas, incluindo item que não possuem combinações em comum
WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT 'TOKIO' AS CITY, 'TOKIO' AS STATE
UNION ALL SELECT 'MUMBAY' AS CITY, 'MAHARASHIRA' AS STATE
UNION ALL SELECT 'A CORUNA' AS CITY, 'GALICIA' AS STATE
UNION ALL SELECT 'SÃO PAULO' AS CITY, 'SÃO PAULO' AS STATE),
FROM_ITEM_B AS
(SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKIO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY
UNION ALL SELECT 'RIO DE JANEIRO' AS STATE, 'BRASIL' AS COUNTRY
UNION ALL SELECT 'MEXICO CITY' AS STATE, 'MEXICO' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A
FULL OUTER JOIN FROM_ITEM_B
ON FROM_ITEM_A.STATE = FROM_ITEM_B.STATE;




















